version: '3.8'

services:
  api:
    container_name: night-view-api
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/wasuwa/night-view-api
    depends_on:
      - postgres
  postgres:
    container_name: night-view-postgres
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
